### ISSUE TITLE
Handle non-existent actions more gracefully

### ISSUE THREAD

**Issue by joshprice** [ash-project/ash_oban#6]
**Is your feature request related to a problem? Please describe.**

Given a trigger setup with a non-existent action:

```elixir
    trigger :send_email do
        action :send_email
        read_action :invalid_action
        queue :emailer
      end
```

I get the following error which doesn't tell me what I did wrong:

```elixir
** (RuntimeError) Exception in transformer AshOban.Transformers.SetDefaults on MyResource:

key :pagination not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
    (ash_oban 0.1.4) lib/transformers/set_defaults.ex:40: anonymous fn/3 in AshOban.Transformers.SetDefaults.transform/1
    (elixir 1.14.4) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ash_oban 0.1.4) lib/transformers/set_defaults.ex:19: AshOban.Transformers.SetDefaults.transform/1
    (spark 1.1.22) lib/spark/dsl/extension.ex:679: anonymous fn/4 in Spark.Dsl.Extension.run_transformers/4
    (elixir 1.14.4) lib/enum.ex:4751: Enumerable.List.reduce/3
    (elixir 1.14.4) lib/enum.ex:2514: Enum.reduce_while/3
```

**Describe the solution you'd like**

An error/warning suggesting that the action doesn't exist would be very helpful. Just like the unpaginated read action warning.

**Additional context**

Not sure if this is an Ash Oban specific issue?

**Comment by zachdaniel** [comment]
Ah, yeah the issue is that we're confirming the actions exist in a validator, but we're *using* them in a transformer before the validator runs. Will address.
